name: juegotodosmienten
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Updated Firebase dependencies to the latest stable versions
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  model_viewer_plus: ^1.7.0
  provider: ^6.0.0
  shared_preferences: ^2.2.3 # Keeping for language/theme persistence

  # SQLite dependencies
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#0E0E0E"
  image: assets/img/logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/models/
    - assets/img/
