name: juegotodosmienten
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  mailer: ^6.1.0
  # State Management & Services
  provider: ^6.0.0
  shared_preferences: ^2.2.3

  # UI & Utilities
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  model_viewer_plus: ^1.7.0
  sqflite: ^2.3.0
  path: ^1.8.3

  # Sharing & Deep Linking
  share_plus: ^9.0.0
  app_links: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#0E0E0E"
  image: assets/img/logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/lang/profanity_filter.json # Added profanity filter
    - assets/lang/colors.json # Added colors definition
    - assets/models/
    - assets/img/
